name: Matrix Demo
on:
    push:
        branches: [master]
jobs:
    build:
        strategy:
            matrix:
                node-version: [12, 14, 16]
                operation-system: [ubuntu-latest, windows-latest]
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4.1.7
            - name: Install Dependencies
              uses: actions/setup-node@v4.0.3
              with:
                node-version: '18'
            - name: Build
              run: npm run build