name: Matrix Demo
on:
  push:
    branches: [master]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Get-Code
        uses: actions/checkout@v4.1.7
      - name: Install NodeJS
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build