name: Matrix Demo
on:
  push:
    branches: [master]
jobs:
  Build:
    strategy:
        matrix:
            operation-system: [ubuntu-latest]
            node-modules: [12,14,18]
    runs-on: ${{matrix.operation-system}}
    steps:
      - name: Get-Code
        uses: actions/checkout@v4.1.7
      - name: Install NodeJS
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{matrix.node-modules}}
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build