name: Reusable-Code
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: The file of the deployable artifacts files
                required: false
                default: dist
                type: string
jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Download a Build Artifact
              uses: actions/download-artifact@v4.1.8
              with:
                name: ${{inputs.artifact-name}}
            - name: "Deploying Code"
              run: echo "Deploying Code"
        